In [1]:
import os
from tensorflow import keras
from transformers import BertTokenizer, TFBertModel
import pandas as pd

In [2]:
df = pd.read_csv('./kpm_data/arguments_train.csv')[['arg_id','argument']]
text = df.iloc[0]['argument']
print( text )

`people reach their limit when it comes to their quality of life and should be able to end their suffering. this can be done with little or no suffering by assistance and the person is able to say good bye.


In [3]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = TFBertModel.from_pretrained("bert-base-uncased")

2022-09-08 09:46:18.428218: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-09-08 09:46:18.429151: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


Metal device set to: Apple M1

systemMemory: 8.00 GB
maxCacheSize: 2.67 GB



Some layers from the model checkpoint at bert-base-uncased were not used when initializing TFBertModel: ['nsp___cls', 'mlm___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


In [5]:
encoded_input = tokenizer(text, return_tensors='tf')
output = model(encoded_input)
output

{'input_ids': <tf.Tensor: shape=(1, 45), dtype=int32, numpy=
array([[ 101, 1036, 2111, 3362, 2037, 5787, 2043, 2009, 3310, 2000, 2037,
        3737, 1997, 2166, 1998, 2323, 2022, 2583, 2000, 2203, 2037, 6114,
        1012, 2023, 2064, 2022, 2589, 2007, 2210, 2030, 2053, 6114, 2011,
        5375, 1998, 1996, 2711, 2003, 2583, 2000, 2360, 2204, 9061, 1012,
         102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 45), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 45), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1]], dtype=int32)>}


TFBaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=<tf.Tensor: shape=(1, 45, 768), dtype=float32, numpy=
array([[[ 0.13353238,  0.35120836, -0.24453926, ..., -0.5796229 ,
          0.35303378,  0.5434918 ],
        [ 0.7771602 ,  0.21784423, -0.09932484, ...,  0.26274127,
          0.5418944 ,  0.00955295],
        [ 0.13640448,  0.04032418, -0.50545186, ..., -0.34002927,
         -0.2095398 , -0.38681906],
        ...,
        [ 1.0495555 , -0.20809034,  0.8531461 , ...,  0.9583427 ,
         -0.35177332, -0.15312147],
        [-0.19968995, -0.5495134 , -0.07066479, ...,  0.54869187,
          0.43997127, -0.4583775 ],
        [ 0.5539042 , -0.01876549,  0.1879522 , ...,  0.06257783,
         -0.36165068, -0.03981954]]], dtype=float32)>, pooler_output=<tf.Tensor: shape=(1, 768), dtype=float32, numpy=
array([[-8.25194597e-01, -6.07195139e-01, -9.72210467e-01,
         8.07408214e-01,  6.84678197e-01, -2.77580023e-01,
         7.73599684e-01,  4.10372823e-01, -9.13315475e-